### ISSUE TITLE
[bug] generate failed when isModifiedCond is 'true'

### ISSUE THREAD

**Issue by earlgray283** [earlgray283/fixgen#16]
```yaml
Hoge:
  fields:
    Fuga:
      isModifiedCond: 'true'
```
