### ISSUE TITLE
[feature] chunk

### ISSUE THREAD

**Issue by earlgray283** [earlgray283/fixgen#17]
## What

複数の table をまとめて作成する fixture を作れるようにする

example

```yaml
chunks:
  UserTodo:
    structs:
      - User
      - Todo
```

↓

```go
func CreateUserTodo(t *testing.T, user *User, todo *Todo) (*CreateUserTodoResult)
```
