### ISSUE TITLE
[feature] custom modify detect condition

### ISSUE THREAD

**Issue by earlgray283** [earlgray283/fixgen#8]
故意的にゼロ値を設定したいケースがあると思うので

```yaml
fields:
  Type:
    modifyCond: 'm.Type != 1`
```
